[package]
name = "octave-langserver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"
